-- 05_business_insights

-- 1. Best Market. 
-- Which country generates the highest revenue, and should the company focus more on this market?
SELECT 
	c.Country,
	COUNT(DISTINCT c."Customer ID") as number_of_customers,
	COUNT (o."Order ID") as number_of_orders,
	ROUND(SUM(o.Quantity * p."Unit Price"),2) as total_revenue,
	ROUND(AVG(o.Quantity * p."Unit Price"),2) as average_order_value
FROM orders o 
JOIN customers c 
	ON o."Customer ID" = c."Customer ID" 
JOIN products p 
	ON o."Product ID" = p."Product ID" 
GROUP BY 1
ORDER BY total_revenue desc;
-- The United States is the company's strongest market, generating more revenue than Ireland and the United Kingdom combined. 
-- It also has the largest customer base and the highest number of orders, indicating strong customer demand. 
-- Although the average order value is only slightly higher than in the other markets, the combination of high customer volume and purchase frequency makes the US the company's most valuable market. 
-- If I had a limited marketing budget, I would prioritize the US because it currently delivers the highest return in terms of sales performance.


-- 2. Loyalty Program Effectiveness. 
-- Do loyalty card holders generate more business value than customers without a loyalty card?
WITH loyalty_card_revenue AS (
	SELECT 
		c."Loyalty Card",
		COUNT(DISTINCT c."Customer ID") as customers,
		COUNT(o."Order ID") as orders,
		AVG(o.Quantity * p."Unit Price") as average_order_revenue,
		SUM(o.Quantity * p."Unit Price") as t_revenue
	FROM orders o 
	JOIN customers c 
		ON o."Customer ID" = c."Customer ID" 
	JOIN products p 
		ON o."Product ID" = p."Product ID" 
	GROUP BY 1
)
	
SELECT 
	"Loyalty Card",
	customers,
	orders,
	ROUND(t_revenue, 2) as total_revenue,
	ROUND(t_revenue/customers,2) as revenue_per_customer,
	ROUND(orders*1.0/customers,2) as orders_per_customer,
	ROUND(average_order_revenue,2) as average_order_value
FROM loyalty_catd_revenue
GROUP BY 1
ORDER BY total_revenue desc;
-- Based on the available data, the current loyalty program does not appear to generate higher customer value. 
-- Customers without a loyalty card generate more total revenue, higher revenue per customer, and a higher average order value. 
-- This suggests that the current loyalty program may not be providing enough incentives to influence customer purchasing behavior.


-- 3. Product Strategy. 
-- If we could advertise only three products next month, which products should we choose?
WITH total_table AS (
	SELECT 
		p."Product ID",
		p."Coffee Type",
		p."Roast Type",
		p.Size,
		COUNT(o."Order ID") as orders,
		SUM(o.Quantity * p."Unit Price") as t_revenue,
		SUM(o.Quantity * p.Profit) as t_profit
	FROM orders o  
	JOIN products p 
		ON o."Product ID" = p."Product ID"
	GROUP BY 1,2,3,4
)

SELECT 
	"Product ID",
	"Coffee Type",
	"Roast Type",
	Size,
	orders,
	ROUND(t_revenue, 2) as total_revenue,
	ROUND(t_profit, 2) as total_profit,
	ROUND(t_profit/t_revenue * 100, 2) as profit_margin
FROM total_table
ORDER BY total_profit desc
LIMIT 4;
-- Products with the highest revenue are not always the most profitable because profit depends on both sales volume and profit per unit. 
-- Some products generate slightly lower revenue but produce significantly higher profit margins, making them better candidates for marketing investment.


-- 4. Sales Concentration Analysis. 
-- What percentage of total revenue is generated by the Top 5 products?
WITH revenue AS (
	SELECT 
		p."Product ID",
		p."Coffee Type",
		p."Roast Type",
		p.Size,
		SUM(o.Quantity * p."Unit Price")  as product_revenue
	FROM orders o 
	JOIN products p 
		ON o."Product ID" = p."Product ID"
	GROUP BY 1,2,3,4
),

revenue_share AS (
	SELECT
		"Product ID",
		"Coffee Type",
		"Roast Type",
		Size,
		product_revenue,
		SUM(product_revenue) OVER () as total_company_revenue,
		SUM(product_revenue) OVER (ORDER BY product_revenue desc) as cumulative_revenue
	FROM revenue
)

SELECT 
	"Product ID",
	"Coffee Type",
	"Roast Type",
	Size,
	ROUND(product_revenue, 2) as total_revenue,
	ROUND(product_revenue/total_company_revenue *100.0,2) as revenue_percentage,
	ROUND(cumulative_revenue/total_company_revenue *100, 2) as cumulative_revenue_percentage
FROM revenue_share
ORDER BY total_revenue DESC 
LIMIT 5;
-- The Top 5 products generate 26.86% of total company revenue. 
-- Each of these products contributes around 5–6% individually, which suggests that sales are relatively well diversified across the product portfolio. 
--The company does not appear to be highly dependent on one or two products. 
--However, these products are still important because they are the strongest revenue drivers. 
--I would recommend maintaining strong inventory levels for these products, but not relying only on them for future growth.
